# Generated by Django 5.2.15 on 2026-07-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('driver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(max_length=255)),
                ('booking_date', models.DateField()),
                ('fare', models.FloatField()),
                ('ride_status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=20)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.IntegerField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Offline', 'Offline')], default='Available', max_length=20)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('booking_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Wallet', 'Wallet'), ('Cash', 'Cash')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateField()),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('SUV', 'SUV'), ('Auto', 'Auto'), ('Bike', 'Bike'), ('Luxury', 'Luxury')], max_length=20)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('seating_capacity', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
    ]
